spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: v1OLYHaEYgTfolx9U1rV
    url: jdbc:postgresql://containers-us-west-50.railway.app:5895/railway
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB

app:
  cloudinary:
    cloud-name: drrydeigb
    api-key: 555972562259279
    api-secret: ZWJcJ99_cLvrIpw4cvoP3y-Hedw

  properties:
    image:
      profile-image-height: 256
      profile-image-width: 256
      movie-image-height: 512
      movie-image-width: 512
      genre-image-height: 512
      genre-image-width: 512
      person-image-height: 512
      person-image-width: 512

  jwt:
    access-token-expiration-millis: 86400000
    secret: secret
